Atoms/ Titleを完成させる
Riku-Obata/riku-frontend-basic-2022-todoapp pull request #1
Opened 2023-09-28 05:24 UTC by Riku-Obata

2023-09-28 08:14 UTC, shimamaru reviewed
初めてのReactですが、スタイリングに関しては良いと思います！

jsx記法とstyeld-componentsの使い方もバッチリです😄

余白や導入してないimportは、消すと綺麗でイイとおもいます

2023-09-28 08:14 UTC, shimamaru commented on src/components/Atoms/Title/index.jsx
余白は消すとイイと思います！

2023-09-28 08:14 UTC, shimamaru commented on src/components/Atoms/Title/index.jsx
> +
こちらも同様です

2023-09-28 08:29 UTC, Riku-Obata commented on src/components/Atoms/Title/index.jsx
> +
修正しました！

2023-09-28 16:06 UTC, higashiji2000 requested changes
Titleコンポーネント自体は完璧です！
余計なファイルやライブラリが存在するので、そちら消してからマージしましょう。

2023-09-28 16:06 UTC, higashiji2000 commented on package.json
> +    "react-responsive": "^9.0.2"
styled-component によってレスポンシブ対応が可能なので、このライブラリは不要です！
`yarn remove react-responsive` でアンインストールしましょう。

参考：https://zenn.dev/mo_ri_regen/articles/yarn-remove-package

2023-09-28 16:06 UTC, higashiji2000 commented on public/main.js
おそらくビルドのコマンドを実行した結果かと思います。
今回はビルドする必要は無いので、このファイルを削除してpushしてください
。

2023-09-28 16:06 UTC, higashiji2000 commented on public/main.js.LICENSE.txt
こちらのファイルも不要なので削除してください！

2023-09-28 16:06 UTC, higashiji2000 commented on src/components/Example/index.jsx
> +  color:
こちら特に理由がなければ元に戻しちゃってよいかと思います。
(11行目が文法エラーになるので)

2023-09-30 00:50 UTC, higashiji2000 approved these changes
見た目問題ないのでLGTMです！

2023-09-30 00:50 UTC, higashiji2000 commented on package-lock.json
このファイルは `npm install` をすると生成されるものです。
今回の課題ではnpmではなくnpm互換のパッケージマネージャーであるyarnを使っているため、このファイル自体不要なのでこちらも削除してしまって大丈夫です。

yarn における yarn.lock が npm における package-lock.json となります。
参考：https://zenn.dev/nekoniki/articles/ec5bb4d16ef20a

2023-09-30 05:22 UTC, merged